0X0C WEB SERVER

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,21 +1,23 @@
 #!/usr/bin/env bash
 # i am gona transfer file to the server using scp and in ssh
-if[$# -lt 4]
+if [ $# -lt 4 ]
 then 
-	echo"Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 	exit 1
+fi
 #assiging paremeters to variables
-path_to_file =$1
+path_to_file=$1
 ip=$2
 user_name=$3
 path_to_ssh_private_key=$4
 
 # disabling strict hostkey cheaking
-scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_private_key" "$path_to_file" "$user_name@ip:~/"
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_private_key" "$path_to_file" "$user_name@$ip:~/"
 # check if the file transfered is successfull
 
-if [$? -eq 0]
+if [ $? -eq 0 ]
+then
 	echo "file transfered is successfull"
 else
-	echo"file transfered Failed"
+	echo "file transfered Failed"
 fi 
